sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.*,**/*.test.*,**/package-lock.json,**/yarn.lock
sonar.test.exclusions=**/*.spec.*,**/*.test.*
sonar.javascript.node.maxspace=4096
